CREATE DATABASE IF NOT EXISTS Minska;

CREATE TABLE IF NOT EXISTS users (
    ID INT NOT NULL AUTO_INCREMENT,
    Firstname VARCHAR(45) NOT NULL,
    Lastname VARCHAR(45) NOT NULL,
    Email VARCHAR(45) NOT NULL,
    Language VARCHAR(45),
    IsFemale BOOLEAN,
    Height DOUBLE,
    Aim_Weight DOUBLE,
    Aim_Date DATE,
    Password VARCHAR(255) NOT NULL,
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ChangeDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_email(Email),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS weights (
    ID INT NOT NULL AUTO_INCREMENT,
    UserID INT NOT NULL,
    Weight DOUBLE,
    MeasureDate DATE NOT NULL,
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (UserID) REFERENCES users(ID)
);

CREATE TABLE IF NOT EXISTS templates (
    ID INT NOT NULL AUTO_INCREMENT,
    UserID INT NOT NULL,
    Title VARCHAR(45) NOT NULL,
    DefaultAmout DOUBLE NOT NULL,
    Calories DOUBLE NOT NULL,
    Image VARCHAR(255),
    Uses INT,
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ChangeDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (UserID) REFERENCES users(ID)
);

CREATE TABLE IF NOT EXISTS calories (
    ID INT NOT NULL AUTO_INCREMENT,
    UserID INT NOT NULL,
    Title VARCHAR(45) NOT NULL,
    Calories DOUBLE NOT NULL,
    Amount DOUBLE NOT NULL,
    Date Date NOT NULL,
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (UserID) REFERENCES users(ID)
);
