CREATE DATABASE IF NOT EXISTS Minska;

CREATE TABLE IF NOT EXISTS Users (
    ID INT NOT NULL AUTO_INCREMENT,
    Firstname VARCHAR(45) NOT NULL,
    Lastname VARCHAR(45) NOT NULL,
    Email VARCHAR(45) NOT NULL,
    Language VARCHAR(45),
    Password VARCHAR(255) NOT NULL,
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ChangeDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_email(Email),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS UserDetails (
    ID INT NOT NULL AUTO_INCREMENT,
    UserID INT NOT NULL,
    IsFemale BOOLEAN,
    Height DOUBLE,
    Weight DOUBLE,
    Picture VARCHAR(255),
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ChangeDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (UserID) REFERENCES Users(ID)
);

CREATE TABLE IF NOT EXISTS UserAims (
    ID INT NOT NULL AUTO_INCREMENT,
    UserID INT NOT NULL,
    Weight DOUBLE,
    Date DATE,
    BMI DOUBLE,
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ChangeDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (UserID) REFERENCES Users(ID)
);

CREATE TABLE IF NOT EXISTS Weights (
    ID INT NOT NULL AUTO_INCREMENT,
    UserID INT NOT NULL,
    Weight DOUBLE,
    MeasureDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ChangeDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (UserID) REFERENCES Users(ID)
);

CREATE TABLE IF NOT EXISTS Foods (
    ID INT NOT NULL AUTO_INCREMENT,
    UserID INT NOT NULL,
    Name VARCHAR(45) NOT NULL,
    DefaultAmout DOUBLE NOT NULL,
    Calories DOUBLE NOT NULL,
    Image VARCHAR(255),
    Uses INT,
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ChangeDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (UserID) REFERENCES Users(ID)
);

CREATE TABLE IF NOT EXISTS Intakes (
    ID INT NOT NULL AUTO_INCREMENT,
    UserID INT NOT NULL,
    FoodID INT NOT NULL,
    Amount DOUBLE NOT NULL,
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (UserID) REFERENCES Users(ID),
    FOREIGN KEY (FoodID) REFERENCES Foods(ID)
);

CREATE TABLE IF NOT EXISTS Logging (
    ID INT NOT NULL AUTO_INCREMENT,
    UserProperty VARCHAR(255) NOT NULL,
    UserIP VARCHAR(255),
    UserReferer VARCHAR(255),
    Action VARCHAR(255) NOT NULL,
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);
